services:
    _defaults:
        autowire: true
        public: true

    App\Service\GameService: ~
    App\Repository\GameRepository: ~
    App\Service\PlayerService: ~
    App\Service\MapService: ~
